from __future__ import annotations

import json
from pathlib import Path
import shlex
import subprocess
import sys

from skillfoundry import initialize_job_workspace, run_forgeunit_command_bridge_pilot_graph
from skillfoundry.graph_v2 import V2Stage, V2Status


REPO_ROOT = Path(__file__).resolve().parents[1]
WRAPPER = REPO_ROOT / "scripts" / "forgeunit_codex_exec_worker.py"
VALID_SKILL = """---
name: forgeunit-wrapper-demo
description: Demo package generated by the fake Codex command.
---

# ForgeUnit Wrapper Demo

## Overview
This fixture validates the real Codex exec wrapper path with a fake command.

## When To Use
Use it when testing the ForgeUnit wrapper integration with SkillFoundry gates.

## When Not To Use
Do not use it as a production skill or as evidence of a live Codex run.

## Inputs
Provide frozen SkillFoundry refs and the ForgeUnit task packet.

## Outputs
Return a verifier-valid SKILL.md package and boundary evidence refs.

## Workflow
1. Read the task context.
2. Write the package.
3. Let the wrapper write protocol evidence.
4. Let SkillFoundry verify and register.

## Safety
Do not put raw prompts, raw transcripts, or package bodies into graph state.
"""

MINIMAL_VALID_SKILL = """---
name: fake-skill
description: "Fake skill used by wrapper boundary tests."
---

# Fake Skill

## Overview
Body.
"""


def test_forgeunit_codex_exec_worker_wraps_fake_codex_and_writes_boundary_result(tmp_path: Path) -> None:
    task_dir, run_dir, worker_result = _forgeunit_env_dirs(tmp_path)
    fake_codex = tmp_path / "fake_codex.py"
    fake_codex.write_text(
        f"""
from pathlib import Path
import sys

prompt = sys.stdin.read()
assert "ForgeUnit Codex Exec Boundary Contract" in prompt
assert "Satisfy every must acceptance criterion" in prompt
assert "Exact H2 headings" in prompt
assert "## When To Use" in prompt
assert "package/SKILL.md" in prompt
Path("package").mkdir(exist_ok=True)
Path("evidence").mkdir(exist_ok=True)
Path("package/SKILL.md").write_text({MINIMAL_VALID_SKILL!r}, encoding="utf-8")
Path("evidence/transcript.md").write_text("fake codex transcript summary\\n", encoding="utf-8")
""".strip(),
        encoding="utf-8",
    )

    completed = _run_wrapper(
        task_dir=task_dir,
        run_dir=run_dir,
        worker_result=worker_result,
        codex_command=f"{sys.executable} {fake_codex}",
    )

    assert completed.returncode == 0, completed.stderr
    assert (task_dir / "package" / "SKILL.md").is_file()
    manifest = json.loads((task_dir / "evidence" / "manifest.json").read_text(encoding="utf-8"))
    result = json.loads(worker_result.read_text(encoding="utf-8"))
    diagnostics = json.loads((run_dir / "workers" / "forgeunit_codex_exec_worker_result.json").read_text())
    assert manifest["schema"] == "forgeunit.worker_evidence_manifest"
    assert manifest["status"] == "completed"
    assert result["status"] == "completed"
    assert result["output_artifacts"][0]["path"] == "package/SKILL.md"
    assert {item["path"] for item in result["boundary_evidence"]} == {
        "evidence/transcript.md",
        "evidence/manifest.json",
    }
    assert diagnostics["returncode"] == 0
    assert diagnostics["raw_prompt_included"] is False
    assert diagnostics["raw_stdout_included"] is False
    assert diagnostics["raw_stderr_included"] is False


def test_forgeunit_codex_exec_worker_reports_missing_package_with_actionable_message(tmp_path: Path) -> None:
    task_dir, run_dir, worker_result = _forgeunit_env_dirs(tmp_path)
    fake_codex = tmp_path / "fake_codex_missing_package.py"
    fake_codex.write_text(
        f"""
from pathlib import Path
import sys

_ = sys.stdin.read()
Path("evidence").mkdir(exist_ok=True)
Path("evidence/transcript.md").write_text("no package was written\\n", encoding="utf-8")
""".strip(),
        encoding="utf-8",
    )

    completed = _run_wrapper(
        task_dir=task_dir,
        run_dir=run_dir,
        worker_result=worker_result,
        codex_command=f"{sys.executable} {fake_codex}",
    )

    assert completed.returncode == 1
    assert "package/SKILL.md was not produced" in completed.stderr
    assert "Expected package/SKILL.md under FORGEUNIT_TASK_DIR" in completed.stderr
    assert not worker_result.exists()


def test_forgeunit_codex_exec_worker_rejects_invalid_skill_frontmatter(tmp_path: Path) -> None:
    task_dir, run_dir, worker_result = _forgeunit_env_dirs(tmp_path)
    fake_codex = tmp_path / "fake_codex_bad_frontmatter.py"
    fake_codex.write_text(
        f"""
from pathlib import Path
import sys

_ = sys.stdin.read()
Path("package").mkdir(exist_ok=True)
Path("package/SKILL.md").write_text(
    "---\\nname: fake\\ndescription: invalid: unquoted colon\\n---\\n\\n# Fake Skill\\n\\n## Overview\\nBody.\\n",
    encoding="utf-8",
)
Path("evidence").mkdir(exist_ok=True)
Path("evidence/transcript.md").write_text("fake codex transcript summary\\n", encoding="utf-8")
""".strip(),
        encoding="utf-8",
    )

    completed = _run_wrapper(
        task_dir=task_dir,
        run_dir=run_dir,
        worker_result=worker_result,
        codex_command=f"{sys.executable} {fake_codex}",
    )

    assert completed.returncode == 1
    assert "frontmatter is invalid YAML" in completed.stderr
    assert "quote frontmatter values containing colons" in completed.stderr
    assert not worker_result.exists()


def test_forgeunit_codex_exec_worker_fails_when_frozen_rust_requirement_is_unmet(tmp_path: Path) -> None:
    task_dir, run_dir, worker_result = _forgeunit_env_dirs(tmp_path)
    (task_dir / "acceptance_criteria.yaml").write_text(
        """
criteria:
- id: AC-RUST
  priority: must
  description: The package must include a Rust verifier with Cargo.toml, src, tests/fixtures, and cargo test.
""".strip(),
        encoding="utf-8",
    )
    fake_codex = tmp_path / "fake_codex_skill_only.py"
    fake_codex.write_text(
        f"""
from pathlib import Path
import sys

_ = sys.stdin.read()
Path("package").mkdir(exist_ok=True)
Path("package/SKILL.md").write_text({MINIMAL_VALID_SKILL!r}, encoding="utf-8")
Path("evidence").mkdir(exist_ok=True)
Path("evidence/transcript.md").write_text("fake codex transcript summary\\n", encoding="utf-8")
""".strip(),
        encoding="utf-8",
    )

    completed = _run_wrapper(
        task_dir=task_dir,
        run_dir=run_dir,
        worker_result=worker_result,
        codex_command=f"{sys.executable} {fake_codex}",
    )

    assert completed.returncode == 1
    assert "requires Rust/Cargo verifier work" in completed.stderr
    assert not worker_result.exists()


def test_forgeunit_codex_exec_worker_accepts_package_level_fixture_directory(tmp_path: Path) -> None:
    task_dir, run_dir, worker_result = _forgeunit_env_dirs(tmp_path)
    (task_dir / "acceptance_criteria.yaml").write_text(
        """
criteria:
- id: AC-RUST
  priority: must
  description: The package must include a Rust verifier with Cargo.toml, src, fixtures, and cargo test evidence.
""".strip(),
        encoding="utf-8",
    )
    fake_codex = tmp_path / "fake_codex_package_fixtures.py"
    fake_codex.write_text(
        """
from pathlib import Path
import sys

_ = sys.stdin.read()
Path("package/src").mkdir(parents=True, exist_ok=True)
Path("package/fixtures/examples").mkdir(parents=True, exist_ok=True)
Path("package/SKILL.md").write_text(__MINIMAL_VALID_SKILL__, encoding="utf-8")
Path("package/Cargo.toml").write_text("[package]\\nname = \\"fake\\"\\nversion = \\"0.1.0\\"\\nedition = \\"2021\\"\\n", encoding="utf-8")
Path("package/src/lib.rs").write_text("pub fn ok() -> bool { true }\\n", encoding="utf-8")
Path("package/fixtures/examples/sample.json").write_text("{}", encoding="utf-8")
Path("evidence").mkdir(exist_ok=True)
Path("evidence/transcript.md").write_text("fake codex transcript summary\\n", encoding="utf-8")
""".strip().replace("__MINIMAL_VALID_SKILL__", repr(MINIMAL_VALID_SKILL)),
        encoding="utf-8",
    )

    completed = _run_wrapper(
        task_dir=task_dir,
        run_dir=run_dir,
        worker_result=worker_result,
        codex_command=f"{sys.executable} {fake_codex}",
    )

    assert completed.returncode == 0, completed.stderr
    result = json.loads(worker_result.read_text(encoding="utf-8"))
    assert "package/fixtures/examples/sample.json" in result["changed_files"]


def test_forgeunit_codex_exec_worker_normalizes_incomplete_existing_manifest(tmp_path: Path) -> None:
    task_dir, run_dir, worker_result = _forgeunit_env_dirs(tmp_path)
    fake_codex = tmp_path / "fake_codex_incomplete_manifest.py"
    fake_codex.write_text(
        """
from pathlib import Path
import json
import sys

_ = sys.stdin.read()
Path("package").mkdir(exist_ok=True)
Path("evidence").mkdir(exist_ok=True)
Path("package/SKILL.md").write_text(__MINIMAL_VALID_SKILL__, encoding="utf-8")
Path("evidence/transcript.md").write_text("fake codex transcript summary\\n", encoding="utf-8")
Path("evidence/manifest.json").write_text(json.dumps({
    "schema": "forgeunit.worker_evidence_manifest",
    "version": "0.6",
    "status": "completed",
    "changed_files": ["package/SKILL.md", "evidence/transcript.md", "evidence/manifest.json"],
    "commands": [{"command": "fake codex", "exit_code": 0}],
    "usage": None,
    "usage_unavailable_reason": "external_worker_no_provider_telemetry"
}, indent=2), encoding="utf-8")
""".strip().replace("__MINIMAL_VALID_SKILL__", repr(MINIMAL_VALID_SKILL)),
        encoding="utf-8",
    )

    completed = _run_wrapper(
        task_dir=task_dir,
        run_dir=run_dir,
        worker_result=worker_result,
        codex_command=f"{sys.executable} {fake_codex}",
    )

    assert completed.returncode == 0, completed.stderr
    manifest = json.loads((task_dir / "evidence" / "manifest.json").read_text(encoding="utf-8"))
    assert manifest["unit_id"] == "execute"
    assert manifest["output_artifacts"][0]["path"] == "package/SKILL.md"
    assert manifest["evidence_artifacts"][0]["path"] == "evidence/transcript.md"
    assert manifest["commands"][0]["summary"] == ""


def test_forgeunit_codex_exec_worker_filters_directory_artifacts_from_existing_worker_result(tmp_path: Path) -> None:
    task_dir, run_dir, worker_result = _forgeunit_env_dirs(tmp_path)
    fake_codex = tmp_path / "fake_codex_directory_worker_result.py"
    fake_codex.write_text(
        """
from pathlib import Path
import json
import os
import sys

_ = sys.stdin.read()
worker_result = Path(os.environ["FORGEUNIT_WORKER_RESULT"])
Path("package/tests/fixtures").mkdir(parents=True, exist_ok=True)
Path("package/SKILL.md").write_text(__MINIMAL_VALID_SKILL__, encoding="utf-8")
Path("package/tests/fixtures/sample.json").write_text("{}", encoding="utf-8")
Path("evidence").mkdir(exist_ok=True)
Path("evidence/transcript.md").write_text("fake codex transcript summary\\n", encoding="utf-8")
Path("evidence/manifest.json").write_text(json.dumps({
    "schema": "forgeunit.worker_evidence_manifest",
    "version": "0.6",
    "unit_id": "execute",
    "status": "completed",
    "output_artifacts": [
        {"path": "package/SKILL.md", "kind": "codex_skill", "summary": "skill"},
    ],
    "evidence_artifacts": [
        {"path": "evidence/transcript.md", "kind": "transcript", "summary": "transcript"},
    ],
    "changed_files": ["package/SKILL.md", "package/tests/fixtures/sample.json", "evidence/transcript.md", "evidence/manifest.json"],
    "commands": [{"command": "fake codex", "exit_code": 0}],
    "usage": None,
    "usage_unavailable_reason": "external_worker_no_provider_telemetry"
}, indent=2), encoding="utf-8")
worker_result.write_text(json.dumps({
    "status": "completed",
    "output_artifacts": [
        {"path": "package/SKILL.md", "kind": "codex_skill", "summary": "skill"},
        {"path": "package/tests/fixtures", "kind": "verifier_fixtures", "summary": "directory should be filtered"},
    ],
    "boundary_evidence": [
        {"path": "evidence/transcript.md", "kind": "transcript", "summary": "transcript"},
        {"path": "evidence/manifest.json", "kind": "worker_evidence_manifest", "summary": "manifest"},
    ],
    "changed_files": [
        "package/SKILL.md",
        "package/tests/fixtures",
        "package/tests/fixtures/sample.json",
        "evidence/transcript.md",
        "evidence/manifest.json",
    ],
    "usage": None,
    "usage_unavailable_reason": "external_worker_no_provider_telemetry"
}, indent=2), encoding="utf-8")
""".strip().replace("__MINIMAL_VALID_SKILL__", repr(MINIMAL_VALID_SKILL)),
        encoding="utf-8",
    )

    completed = _run_wrapper(
        task_dir=task_dir,
        run_dir=run_dir,
        worker_result=worker_result,
        codex_command=f"{sys.executable} {fake_codex}",
    )

    assert completed.returncode == 0, completed.stderr
    result = json.loads(worker_result.read_text(encoding="utf-8"))
    artifact_paths = [item["path"] for item in result["output_artifacts"]]
    assert "package/tests/fixtures" not in artifact_paths
    assert "package/tests/fixtures" not in result["changed_files"]
    assert "package/tests/fixtures/sample.json" in result["changed_files"]


def test_forgeunit_codex_exec_worker_allows_declared_adaptive_attempt_scope(tmp_path: Path) -> None:
    task_dir, run_dir, worker_result = _forgeunit_env_dirs(tmp_path)
    (task_dir / "task.yaml").write_text(
        """
units:
  execute:
    worker:
      write_scope:
        - package
        - evidence
        - adaptive/attempts/003
""".strip(),
        encoding="utf-8",
    )
    fake_codex = tmp_path / "fake_codex_adaptive_scope.py"
    fake_codex.write_text(
        """
from pathlib import Path
import json
import os
import sys

prompt = sys.stdin.read()
assert "`adaptive/attempts/003/`" in prompt
worker_result = Path(os.environ["FORGEUNIT_WORKER_RESULT"])
Path("package").mkdir(exist_ok=True)
Path("evidence").mkdir(exist_ok=True)
Path("adaptive/attempts/003").mkdir(parents=True, exist_ok=True)
Path("package/SKILL.md").write_text(__MINIMAL_VALID_SKILL__, encoding="utf-8")
Path("evidence/transcript.md").write_text("adaptive repair transcript summary\\n", encoding="utf-8")
Path("adaptive/attempts/003/repair_evidence.md").write_text("repair evidence\\n", encoding="utf-8")
worker_result.write_text(json.dumps({
    "status": "completed",
    "output_artifacts": [
        {"path": "package/SKILL.md", "kind": "codex_skill", "summary": "skill"},
    ],
    "boundary_evidence": [
        {"path": "evidence/transcript.md", "kind": "transcript", "summary": "transcript"},
    ],
    "changed_files": [
        "package/SKILL.md",
        "evidence/transcript.md",
        "adaptive/attempts/003/repair_evidence.md",
    ],
    "usage": None,
    "usage_unavailable_reason": "external_worker_no_provider_telemetry"
}, indent=2), encoding="utf-8")
""".strip().replace("__MINIMAL_VALID_SKILL__", repr(MINIMAL_VALID_SKILL)),
        encoding="utf-8",
    )

    completed = _run_wrapper(
        task_dir=task_dir,
        run_dir=run_dir,
        worker_result=worker_result,
        codex_command=f"{sys.executable} {fake_codex}",
    )

    assert completed.returncode == 0, completed.stderr
    result = json.loads(worker_result.read_text(encoding="utf-8"))
    manifest = json.loads((task_dir / "evidence" / "manifest.json").read_text(encoding="utf-8"))
    assert "adaptive/attempts/003/repair_evidence.md" in result["changed_files"]
    assert "adaptive/attempts/003/repair_evidence.md" in manifest["changed_files"]


def test_forgeunit_codex_exec_worker_rejects_undeclared_adaptive_attempt_scope(tmp_path: Path) -> None:
    task_dir, run_dir, worker_result = _forgeunit_env_dirs(tmp_path)
    (task_dir / "task.yaml").write_text(
        """
units:
  execute:
    worker:
      write_scope:
        - package
        - evidence
""".strip(),
        encoding="utf-8",
    )
    fake_codex = tmp_path / "fake_codex_undeclared_adaptive_scope.py"
    fake_codex.write_text(
        """
from pathlib import Path
import json
import os
import sys

_ = sys.stdin.read()
worker_result = Path(os.environ["FORGEUNIT_WORKER_RESULT"])
Path("package").mkdir(exist_ok=True)
Path("evidence").mkdir(exist_ok=True)
Path("adaptive/attempts/003").mkdir(parents=True, exist_ok=True)
Path("package/SKILL.md").write_text(__MINIMAL_VALID_SKILL__, encoding="utf-8")
Path("evidence/transcript.md").write_text("adaptive repair transcript summary\\n", encoding="utf-8")
Path("adaptive/attempts/003/repair_evidence.md").write_text("repair evidence\\n", encoding="utf-8")
worker_result.write_text(json.dumps({
    "status": "completed",
    "output_artifacts": [
        {"path": "package/SKILL.md", "kind": "codex_skill", "summary": "skill"},
    ],
    "boundary_evidence": [
        {"path": "evidence/transcript.md", "kind": "transcript", "summary": "transcript"},
    ],
    "changed_files": [
        "package/SKILL.md",
        "evidence/transcript.md",
        "adaptive/attempts/003/repair_evidence.md",
    ],
    "usage": None,
    "usage_unavailable_reason": "external_worker_no_provider_telemetry"
}, indent=2), encoding="utf-8")
""".strip().replace("__MINIMAL_VALID_SKILL__", repr(MINIMAL_VALID_SKILL)),
        encoding="utf-8",
    )

    completed = _run_wrapper(
        task_dir=task_dir,
        run_dir=run_dir,
        worker_result=worker_result,
        codex_command=f"{sys.executable} {fake_codex}",
    )

    assert completed.returncode == 1
    assert "outside ForgeUnit write scope" in completed.stderr
    assert "adaptive/attempts/003/repair_evidence.md" in completed.stderr


def test_forgeunit_codex_exec_worker_allows_protocol_worker_result_ref(tmp_path: Path) -> None:
    task_dir, run_dir, worker_result = _forgeunit_env_dirs(tmp_path)
    worker_result_ref = worker_result.relative_to(task_dir).as_posix()
    fake_codex = tmp_path / "fake_codex_protocol_worker_result_ref.py"
    fake_codex.write_text(
        f"""
from pathlib import Path
import json
import os
import sys

_ = sys.stdin.read()
worker_result = Path(os.environ["FORGEUNIT_WORKER_RESULT"])
Path("package").mkdir(exist_ok=True)
Path("evidence").mkdir(exist_ok=True)
Path("package/SKILL.md").write_text(__MINIMAL_VALID_SKILL__, encoding="utf-8")
Path("evidence/transcript.md").write_text("protocol worker result transcript summary\\n", encoding="utf-8")
worker_result.write_text(json.dumps({{
    "status": "completed",
    "output_artifacts": [
        {{"path": "package/SKILL.md", "kind": "codex_skill", "summary": "skill"}},
    ],
    "boundary_evidence": [
        {{"path": "evidence/transcript.md", "kind": "transcript", "summary": "transcript"}},
    ],
    "changed_files": [
        "package/SKILL.md",
        "evidence/transcript.md",
        {worker_result_ref!r},
    ],
    "usage": None,
    "usage_unavailable_reason": "external_worker_no_provider_telemetry"
}}, indent=2), encoding="utf-8")
""".strip().replace("__MINIMAL_VALID_SKILL__", repr(MINIMAL_VALID_SKILL)),
        encoding="utf-8",
    )

    completed = _run_wrapper(
        task_dir=task_dir,
        run_dir=run_dir,
        worker_result=worker_result,
        codex_command=f"{sys.executable} {fake_codex}",
    )

    assert completed.returncode == 0, completed.stderr
    result = json.loads(worker_result.read_text(encoding="utf-8"))
    assert worker_result_ref in result["changed_files"]


def test_forgeunit_real_codex_exec_wrapper_can_drive_command_bridge_graph(tmp_path: Path) -> None:
    runs_root = tmp_path / "runs"
    registry_path = tmp_path / "registry.json"
    workspace = initialize_job_workspace(
        runs_root,
        "forgeunit-wrapper-graph-001",
        worker_input="private wrapper graph request must stay outside graph state",
    )
    fake_codex = tmp_path / "fake_codex_graph.py"
    fake_codex.write_text(
        f"""
from pathlib import Path
import sys

prompt = sys.stdin.read()
assert "ForgeUnit Codex Exec Boundary Contract" in prompt
Path("package").mkdir(exist_ok=True)
Path("evidence").mkdir(exist_ok=True)
Path("package/SKILL.md").write_text({VALID_SKILL!r}, encoding="utf-8")
Path("evidence/transcript.md").write_text("fake wrapper graph transcript\\n", encoding="utf-8")
""".strip(),
        encoding="utf-8",
    )
    command = " ".join(
        [
            shlex.quote(sys.executable),
            shlex.quote(WRAPPER.as_posix()),
            "--codex-command",
            shlex.quote(f"{sys.executable} {fake_codex}"),
        ]
    )

    state = run_forgeunit_command_bridge_pilot_graph(
        runs_root,
        workspace.job_id,
        registry_path=registry_path,
        command=command,
        version="wrapper-graph-pilot",
        created_at="2026-05-23T00:00:00Z",
    )
    serialized = json.dumps(state)

    assert state["stage"] == V2Stage.EMIT_REPORT.value
    assert state["status"] == V2Status.REPORT_EMITTED.value
    assert state["contextforge"]["last_verification_status"] == "passed"
    assert state["contextforge"]["registry_approved"] is True
    assert "private wrapper graph request" not in serialized
    assert "ForgeUnit Wrapper Demo" not in serialized
    assert "fake wrapper graph transcript" not in serialized


def _forgeunit_env_dirs(tmp_path: Path) -> tuple[Path, Path, Path]:
    task_dir = tmp_path / "task"
    run_dir = task_dir / ".forgeunit" / "runs" / "run-001"
    worker_result = run_dir / "workers" / "execute_codex_exec_worker_result.json"
    (run_dir / "workers").mkdir(parents=True)
    return task_dir, run_dir, worker_result


def _run_wrapper(
    *,
    task_dir: Path,
    run_dir: Path,
    worker_result: Path,
    codex_command: str,
) -> subprocess.CompletedProcess[str]:
    env = {
        "FORGEUNIT_TASK_DIR": task_dir.as_posix(),
        "FORGEUNIT_RUN_DIR": run_dir.as_posix(),
        "FORGEUNIT_UNIT": "execute",
        "FORGEUNIT_WORKER_RESULT": worker_result.as_posix(),
    }
    return subprocess.run(
        [sys.executable, WRAPPER.as_posix(), "--codex-command", codex_command],
        cwd=REPO_ROOT,
        env=env,
        input="private prompt body should only go to the fake codex stdin",
        text=True,
        capture_output=True,
        check=False,
    )
