from __future__ import annotations

import json
from pathlib import Path
import shlex
import subprocess
import sys

from skillfoundry import initialize_job_workspace, run_forgeunit_command_bridge_pilot_graph
from skillfoundry.graph_v2 import V2Stage, V2Status


REPO_ROOT = Path(__file__).resolve().parents[1]
WRAPPER = REPO_ROOT / "scripts" / "forgeunit_codex_exec_worker.py"
VALID_SKILL = """---
name: forgeunit-wrapper-demo
description: Demo package generated by the fake Codex command.
---

# ForgeUnit Wrapper Demo

## Overview
This fixture validates the real Codex exec wrapper path with a fake command.

## When To Use
Use it when testing the ForgeUnit wrapper integration with SkillFoundry gates.

## When Not To Use
Do not use it as a production skill or as evidence of a live Codex run.

## Inputs
Provide frozen SkillFoundry refs and the ForgeUnit task packet.

## Outputs
Return a verifier-valid SKILL.md package and boundary evidence refs.

## Workflow
1. Read the task context.
2. Write the package.
3. Let the wrapper write protocol evidence.
4. Let SkillFoundry verify and register.

## Safety
Do not put raw prompts, raw transcripts, or package bodies into graph state.
"""


def test_forgeunit_codex_exec_worker_wraps_fake_codex_and_writes_boundary_result(tmp_path: Path) -> None:
    task_dir, run_dir, worker_result = _forgeunit_env_dirs(tmp_path)
    fake_codex = tmp_path / "fake_codex.py"
    fake_codex.write_text(
        """
from pathlib import Path
import sys

prompt = sys.stdin.read()
assert "ForgeUnit Codex Exec Boundary Contract" in prompt
assert "package/SKILL.md" in prompt
Path("package").mkdir(exist_ok=True)
Path("evidence").mkdir(exist_ok=True)
Path("package/SKILL.md").write_text("# Fake Skill\\n\\n## Overview\\nBody.\\n", encoding="utf-8")
Path("evidence/transcript.md").write_text("fake codex transcript summary\\n", encoding="utf-8")
""".strip(),
        encoding="utf-8",
    )

    completed = _run_wrapper(
        task_dir=task_dir,
        run_dir=run_dir,
        worker_result=worker_result,
        codex_command=f"{sys.executable} {fake_codex}",
    )

    assert completed.returncode == 0, completed.stderr
    assert (task_dir / "package" / "SKILL.md").is_file()
    manifest = json.loads((task_dir / "evidence" / "manifest.json").read_text(encoding="utf-8"))
    result = json.loads(worker_result.read_text(encoding="utf-8"))
    diagnostics = json.loads((run_dir / "workers" / "forgeunit_codex_exec_worker_result.json").read_text())
    assert manifest["schema"] == "forgeunit.worker_evidence_manifest"
    assert manifest["status"] == "completed"
    assert result["status"] == "completed"
    assert result["output_artifacts"][0]["path"] == "package/SKILL.md"
    assert {item["path"] for item in result["boundary_evidence"]} == {
        "evidence/transcript.md",
        "evidence/manifest.json",
    }
    assert diagnostics["returncode"] == 0
    assert diagnostics["raw_prompt_included"] is False
    assert diagnostics["raw_stdout_included"] is False
    assert diagnostics["raw_stderr_included"] is False


def test_forgeunit_codex_exec_worker_reports_missing_package_with_actionable_message(tmp_path: Path) -> None:
    task_dir, run_dir, worker_result = _forgeunit_env_dirs(tmp_path)
    fake_codex = tmp_path / "fake_codex_missing_package.py"
    fake_codex.write_text(
        """
from pathlib import Path
import sys

_ = sys.stdin.read()
Path("evidence").mkdir(exist_ok=True)
Path("evidence/transcript.md").write_text("no package was written\\n", encoding="utf-8")
""".strip(),
        encoding="utf-8",
    )

    completed = _run_wrapper(
        task_dir=task_dir,
        run_dir=run_dir,
        worker_result=worker_result,
        codex_command=f"{sys.executable} {fake_codex}",
    )

    assert completed.returncode == 1
    assert "package/SKILL.md was not produced" in completed.stderr
    assert "Expected package/SKILL.md under FORGEUNIT_TASK_DIR" in completed.stderr
    assert not worker_result.exists()


def test_forgeunit_real_codex_exec_wrapper_can_drive_command_bridge_graph(tmp_path: Path) -> None:
    runs_root = tmp_path / "runs"
    registry_path = tmp_path / "registry.json"
    workspace = initialize_job_workspace(
        runs_root,
        "forgeunit-wrapper-graph-001",
        worker_input="private wrapper graph request must stay outside graph state",
    )
    fake_codex = tmp_path / "fake_codex_graph.py"
    fake_codex.write_text(
        f"""
from pathlib import Path
import sys

prompt = sys.stdin.read()
assert "ForgeUnit Codex Exec Boundary Contract" in prompt
Path("package").mkdir(exist_ok=True)
Path("evidence").mkdir(exist_ok=True)
Path("package/SKILL.md").write_text({VALID_SKILL!r}, encoding="utf-8")
Path("evidence/transcript.md").write_text("fake wrapper graph transcript\\n", encoding="utf-8")
""".strip(),
        encoding="utf-8",
    )
    command = " ".join(
        [
            shlex.quote(sys.executable),
            shlex.quote(WRAPPER.as_posix()),
            "--codex-command",
            shlex.quote(f"{sys.executable} {fake_codex}"),
        ]
    )

    state = run_forgeunit_command_bridge_pilot_graph(
        runs_root,
        workspace.job_id,
        registry_path=registry_path,
        command=command,
        version="wrapper-graph-pilot",
        created_at="2026-05-23T00:00:00Z",
    )
    serialized = json.dumps(state)

    assert state["stage"] == V2Stage.EMIT_REPORT.value
    assert state["status"] == V2Status.REPORT_EMITTED.value
    assert state["contextforge"]["last_verification_status"] == "passed"
    assert state["contextforge"]["registry_approved"] is True
    assert "private wrapper graph request" not in serialized
    assert "ForgeUnit Wrapper Demo" not in serialized
    assert "fake wrapper graph transcript" not in serialized


def _forgeunit_env_dirs(tmp_path: Path) -> tuple[Path, Path, Path]:
    task_dir = tmp_path / "task"
    run_dir = task_dir / ".forgeunit" / "runs" / "run-001"
    worker_result = run_dir / "workers" / "execute_codex_exec_worker_result.json"
    (run_dir / "workers").mkdir(parents=True)
    return task_dir, run_dir, worker_result


def _run_wrapper(
    *,
    task_dir: Path,
    run_dir: Path,
    worker_result: Path,
    codex_command: str,
) -> subprocess.CompletedProcess[str]:
    env = {
        "FORGEUNIT_TASK_DIR": task_dir.as_posix(),
        "FORGEUNIT_RUN_DIR": run_dir.as_posix(),
        "FORGEUNIT_UNIT": "execute",
        "FORGEUNIT_WORKER_RESULT": worker_result.as_posix(),
    }
    return subprocess.run(
        [sys.executable, WRAPPER.as_posix(), "--codex-command", codex_command],
        cwd=REPO_ROOT,
        env=env,
        input="private prompt body should only go to the fake codex stdin",
        text=True,
        capture_output=True,
        check=False,
    )
