"""SkillFoundry WP1 workspace and schema primitives."""

from .schema import (
    ApprovalRecord,
    ArtifactManifest,
    ArtifactRecord,
    BuildContract,
    ExecutionReport,
    RegistryEntry,
    RepairAttempt,
    SchemaValidationError,
    SkillSpec,
    VerificationResult,
    VerificationSpec,
    WorkerInvocation,
    canonical_json_bytes,
    sha256_bytes,
    sha256_file,
    sha256_json,
)
from .security import PathSecurityError, assert_under_root, resolve_under_root, validate_relative_path
from .workspace import (
    LOCKED_INPUT_PATHS,
    JobWorkspace,
    LockedInputTamperError,
    initialize_job_workspace,
    verify_locked_inputs,
)

__all__ = [
    "ApprovalRecord",
    "ArtifactManifest",
    "ArtifactRecord",
    "BuildContract",
    "ExecutionReport",
    "JobWorkspace",
    "LOCKED_INPUT_PATHS",
    "LockedInputTamperError",
    "PathSecurityError",
    "RegistryEntry",
    "RepairAttempt",
    "SchemaValidationError",
    "SkillSpec",
    "VerificationResult",
    "VerificationSpec",
    "WorkerInvocation",
    "assert_under_root",
    "canonical_json_bytes",
    "initialize_job_workspace",
    "resolve_under_root",
    "sha256_bytes",
    "sha256_file",
    "sha256_json",
    "validate_relative_path",
    "verify_locked_inputs",
]
